<?xml version="1.0" encoding="UTF-8"?>
<definitions
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://impl.service.fiap.com.br/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://impl.service.fiap.com.br/"
	name="CompraServiceImplService">
	<import namespace="http://service.fiap.com.br/" location="http://localhost:9999/compra?wsdl=1" />
	<binding xmlns:ns1="http://service.fiap.com.br/" name="CompraServiceImplPortBinding"
		type="ns1:CompraService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="aprovarCredito">
			<soap:operation soapAction="https://fiap.com.br/compra/aprovarCredito" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="confirmarCompra">
			<soap:operation soapAction="https://fiap.com.br/compra/confirmar" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="CompraServiceImplService">
		<port name="CompraServiceImplPort" binding="tns:CompraServiceImplPortBinding">
			<soap:address location="http://localhost:9999/compra" />
		</port>
	</service>
</definitions>
